version: '3'
services:
  immer-auch-backend:
    container_name: immer-auch-backend
    image: jailbreakereu/immer-auch-backend:latest
    #platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - immer-auch-db
    network_mode: "host"

  immer-auch-metabase:
    container_name: immer-auch-metabase
    image: 'metabase/metabase:latest'
    platform: linux/amd64
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - immer-auch-metabase-db
    volumes:
      - immer-auch-metabase:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5433
      MB_DB_USER: metabase
      MB_DB_HOST: immer-auch-metabase-db
      MB_DB_PASS: password
    networks:
      - immer_auch_network

  immer-auch-metabase-db:
    container_name: immer-auch-metabase-db
    image: 'postgres:15.4-alpine3.17'
    platform: linux/amd64
    volumes:
      - immer-auch-metabase-db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: password
    command: -p 5433
    networks:
      - immer_auch_network

  immer-auch-db:
    container_name: immer-auch-db
    image: 'arm64v8/postgres:15.5'
    #platform: linux/amd64
    volumes:
      - immer-auch-db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    command: -p 5432
    network_mode: "host"

volumes:
  immer-auch-db:
  immer-auch-metabase-db:
  immer-auch-metabase:

networks:
  immer_auch_network:
    driver: bridge
